# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            John Gadbois
tagline:          'A web developer'
description:      'Christian, father of 3, web developer, CTO of WeightTraining.com'
url:              http://jgadbois.github.io
baseurl:          /

author:
  name:           'John Gadbois'
  url:            https://twitter.com/johngadbois

paginate:         5

# Custom vars
#version:          2.1.0
#github:
#  repo:           https://github.com/poole/hyde
